name: CI

on:
  push:
    branches:
      - main
    paths:
      - '**.rb'
  pull_request:
    paths:
      - '**.rb'

env:
  HOMEBREW_DEVELOPER: 1
  HOMEBREW_NO_ANALYTICS: 1

defaults:
  run:
    shell: bash -xeuo pipefail {0}

jobs:
  test-bot:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/homebrew/brew:main
    permissions:
      actions: read
      checks: read
      contents: read
      pull-requests: read
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main
        with:
          cask: false
          core: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cleanup runner
        run: brew test-bot --only-cleanup-before

      - name: Setup Homebrew test environment
        run: brew test-bot --only-setup

      - run: brew test-bot --only-tap-syntax
  label-pr:
    needs: test-bot
    if: ${{ startsWith(github.head_ref, 'bump') && github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
    - id: label-the-PR
      env:
        GH_TOKEN: ${{secrets.AUTOBUMP_TOKEN}}
        PR_NUMBER: ${{ github.event.pull_request.number }}
      run: gh pr edit "${PR_NUMBER}" --add-label "pr-pull" --repo "otsge/homebrew-casks2"
